version: '3.9'
services:
    postgres:
        image: 'postgres'
        environment:
            - PGPASSWORD=postgres_password
            - POSTGRESS_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
    redis:
        image: 'redis'
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
            - api
            - client
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            # Anytime we have a service that we want to connect to we can just do the below
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            # PGUSER & PGHOST & PGDATABASE is the name of the postgres db service docker-compose.yml file
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - POSTGRES_PASSWORD=password
            - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
